---
- name: ✅ Simulate Closing Incident and Change Request in ServiceNow
  hosts: localhost
  gather_facts: false
  vars:
    incident_number: "INC0010001"
    change_request_number: "CHG0030007"

  tasks:
    - name: 🔍 Pretend to look up Incident and Change Request
      debug:
        msg: "Looking up incident {{ incident_number }} and change request {{ change_request_number }}..."

    - name: ✅ Simulate closing the Incident
      debug:
        msg: "Incident {{ incident_number }} closed with resolution 'SQL Injection remediated successfully'."

    - name: ✅ Simulate closing the Change Request
      debug:
        msg: "Change Request {{ change_request_number }} closed successfully after fix was verified."

    - name: 🎉 Done
      debug:
        msg: "Both records are now closed (visually!)."
