---
- name: Create Change Request in ServiceNow
  hosts: localhost
  gather_facts: no

  vars:
    servicenow_instance: "https://dev181327.service-now.com"
    servicenow_user: "admin"
    servicenow_password: "6kqg0Sr^ZR-V"
    change_short_description: "Emergency Change for WebGoat Vulnerability"
    change_description: "Follow-up change after incident related to SQL Injection exploit"
    input_file: "/tmp/incident_response.json"

  tasks:
    - name: Load incident sys_id from file
      set_fact:
        incident_data: "{{ lookup('file', input_file) | from_json }}"
        incident_sys_id: "{{ (lookup('file', input_file) | from_json).sys_id }}"

    - name: Create change request in ServiceNow
      uri:
        url: "{{ servicenow_instance }}/api/now/table/change_request"
        method: POST
        user: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        validate_certs: no
        headers:
          Content-Type: "application/json"
          Accept: "application/json"
        body_format: json
        body:
          short_description: "{{ change_short_description }}"
          description: "{{ change_description }}"
          correlation_id: "{{ incident_sys_id }}"
      register: change_response
      failed_when: change_response.status | default(0) != 201
      ignore_errors: true

    - name: Show change request number
      debug:
        msg: "Change Request Created: {{ change_response.json.result.number | default('Unknown') }}"
