---
- name: Create Change Request in ServiceNow
  hosts: localhost
  gather_facts: no
  vars_files:
    - /tmp/incident_vars.yml
  vars:
    servicenow_instance: "https://dev181327.service-now.com"
    servicenow_user: "admin"
    servicenow_password: "6kqg0Sr^ZR-V"
    change_short_description: "SQL Injection Fix Deployment"
    change_description: "Automated fix for WebGoat SQL injection issue"

  tasks:
    - name: Create change request in ServiceNow
      uri:
        url: "{{ servicenow_instance }}/api/now/table/change_request"
        method: POST
        user: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        validate_certs: no
        headers:
          Content-Type: "application/json"
          Accept: "application/json"
        body_format: json
        body:
          short_description: "{{ change_short_description }}"
          description: "{{ change_description }}"
          incident: "{{ incident_sys_id }}"
      register: change_response
      ignore_errors: yes
      failed_when: false
      # no_log removed so we can see output

    - name: Show change request number
      debug:
        msg: "Change Request Created: {{ change_response.json.result.number | default('UNKNOWN') }}"
