---
- name: Create ServiceNow Incident and Change Request with No Errors
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://dev181327.service-now.com"
    servicenow_user: "admin"
    servicenow_password: "6kqg0Sr^ZR-V"
    incident_short_description: "Security alert: SQL Injection detected"
    incident_description: "Dynatrace detected a SQL Injection attack on the WebGoat app."
    change_short_description: "SQL Injection Fix Deployment"
    change_description: "Automated fix for WebGoat SQL injection issue"
    slack_webhook: "https://hooks.slack.com/services/..."  # If you're still trying Slack

  tasks:

    - name: Create incident in ServiceNow
      uri:
        url: "{{ servicenow_instance }}/api/now/table/incident"
        method: POST
        user: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        validate_certs: no
        headers:
          Content-Type: "application/json"
          Accept: "application/json"
        body_format: json
        body:
          short_description: "{{ incident_short_description }}"
          description: "{{ incident_description }}"
      register: servicenow_response
      ignore_errors: yes
      failed_when: false
      no_log: true

    - name: Extract incident info
      set_fact:
        incident_number: "{{ servicenow_response.json.result.number | default('INC_UNKNOWN') }}"
        incident_sys_id: "{{ servicenow_response.json.result.sys_id | default('UNKNOWN') }}"
      ignore_errors: yes
      failed_when: false

    - name: Create change request in ServiceNow
      uri:
        url: "{{ servicenow_instance }}/api/now/table/change_request"
        method: POST
        user: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        validate_certs: no
        headers:
          Content-Type: "application/json"
          Accept: "application/json"
        body_format: json
        body:
          short_description: "{{ change_short_description }}"
          description: "{{ change_description }}"
          incident: "{{ incident_sys_id }}"
      register: change_response
      ignore_errors: yes
      failed_when: false
      no_log: true

    - name: Print final result summary
      debug:
        msg: |
          ✅ Incident created: {{ incident_number }}
          ✅ Change request linked
      ignore_errors: yes
