---
- name: Create Incident in ServiceNow
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://dev181327.service-now.com"
    servicenow_user: "admin"
    servicenow_password: "6kqg0Sr^ZR-V"
    incident_short_description: "Security alert: SQL Injection detected"
    incident_description: "Dynatrace detected a SQL Injection attack on the WebGoat app."

  tasks:
    - name: Create incident in ServiceNow
      uri:
        url: "{{ servicenow_instance }}/api/now/table/incident"
        method: POST
        user: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        validate_certs: no
        headers:
          Content-Type: "application/json"
          Accept: "application/json"
        body_format: json
        body:
          short_description: "{{ incident_short_description }}"
          description: "{{ incident_description }}"
      register: incident_response
      ignore_errors: yes
      failed_when: false
      no_log: true

    - name: Save incident sys_id and number for next playbook
      copy:
        dest: /tmp/incident_vars.yml
        content: |
          incident_sys_id: "{{ incident_response.json.result.sys_id | default('UNKNOWN') }}"
          incident_number: "{{ incident_response.json.result.number | default('INC_UNKNOWN') }}"
      delegate_to: localhost

    - name: Show incident result
      debug:
        msg: "Incident Created: {{ incident_response.json.result.number | default('UNKNOWN') }}"
