---
- name: Discover All Dictionary Fields for Incident Table in ServiceNow
  hosts: localhost
  gather_facts: false
  vars:
    servicenow_instance: "https://dev181327.service-now.com"
    servicenow_user: "admin"
    servicenow_password: "6kqg0Sr^ZR-V"

  tasks:

    - name: Get all dictionary entries for incident table
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sys_dictionary?sysparm_query=name=incident&sysparm_limit=500"
        method: GET
        user: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        validate_certs: no
        headers:
          Accept: "application/json"
      register: all_dictionary_fields

    - name: Filter and show fields with internal_type=choice
      debug:
        msg: "{{ item.element }} - {{ item.column_label }}"
      loop: "{{ all_dictionary_fields.json.result | selectattr('internal_type', 'equalto', 'choice') | list }}"
