---
- name: Send Slack test message
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Send test notification to Slack
      uri:
        url: "https://hooks.slack.com/services/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"
        method: POST
        headers:
          Content-Type: "application/json"
        body: '{"text": ":rocket: *Ansible Slack Webhook Test – Success!*"}'
        body_format: raw
