---
- name: Send Slack notification using curl
  hosts: localhost
  gather_facts: no
  vars:
    slack_webhook_url: "https://hooks.slack.com/services/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"
    slack_message: ':rocket: *Slack Webhook Test – Working via curl!*'

  tasks:
    - name: Post to Slack using curl
      command: >
        curl -X POST -H 'Content-type: application/json'
        --data '{{ {"text": slack_message} | to_json }}'
        {{ slack_webhook_url }}
